
// --------------------- BUSINESS SETTINGS TYPES ---------------------
export const SETTINGS_BUSINESS_CHANGE_EMAIL = 'SETTINGS_BUSINESS_CHANGE_EMAIL'
export const SETTINGS_BUSINESS_CHANGE_NAME = 'SETTINGS_BUSINESS_CHANGE_NAME'
export const SETTINGS_BUSINESS_CHANGE_SHIPPING_ADDRESS =
    'SETTINGS_BUSINESS_CHANGE_SHIPPING_ADDRESS'
export const SETTINGS_BUSINESS_CHANGE_BILLING_ADDRESS =
    'SETTINGS_BUSINESS_CHANGE_BILLING_ADDRESS'
export const SETTINGS_BUSINESS_CHANGE_CONTACT_NUMBER =
    'SETTINGS_BUSINESS_CHANGE_CONTACT_NUMBER'
export const SETTINGS_BUSINESS_CHANGE_PROFILE_PICTURE =
    'SETTINGS_BUSINESS_CHANGE_PROFILE_PICTURE'


// ------------------------ PARTNER WEBSITE SETTINGS TYPES -----------------------

export const SETTINGS_PARTNER_WEBSITE_CHANGE_API_KEY =
    'SETTINGS_PARTNER_WEBSITE_CHANGE_API_KEY'
export const SETTINGS_PARTNER_WEBSITE_DELETE_API_KEY =
    'SETTINGS_PARTNER_WEBSITE_DELETE_API_KEY'
export const SETTINGS_PARTNER_WEBSITE_CHANGE_DOMAIN_URL =
    'SETTINGS_PARTNER_WEBSITE_CHANGE_DOMAIN_URL'
export const SETTINGS_PARTNER_WEBSITE_CHANGE_DOMAIN_VERIFICATION =
    'SETTINGS_PARTNER_WEBSITE_CHANGE_DOMAIN_VERIFICATION'
export const SETTINGS_PARTNER_WEBSITE_CHANGE_DOMAIN_VERIFICATION_LOADING =
    'SETTINGS_PARTNER_WEBSITE_CHANGE_DOMAIN_VERIFICATION_LOADING'

// ----------------------- SYSTEM SETTINGS TYPES ---------------------
export const SETTINGS_SYSTEM_CHANGE_PLATFORM_NOTIFICATIONS =
    'SETTINGS_SYSTEM_CHANGE_PLATFORM_NOTIFICATIONS'
export const SETTINGS_SYSTEM_CHANGE_ALL_NOTIFICATIONS = 'SETTINGS_SYSTEM_CHANGE_ALL_NOTIFICATIONS'
export const SETTINGS_SYSTEM_CHANGE_CLIENTS_LIST_TYPE =
    'SETTINGS_SYSTEM_CHANGE_CLIENTS_LIST_TYPE'

// ------------------ USER SETTINGS TYPES -------------------------
export const SETTINGS_USER_CHANGE_NAME = 'SETTINGS_USER_CHANGE_NAME'
export const SETTINGS_USER_CHANGE_EMAIL = 'SETTINGS_USER_CHANGE_EMAIL'
export const SETTINGS_USER_CHANGE_STATE = 'SETTINGS_USER_CHANGE_STATE'
export const SETTINGS_USER_CHANGE_CITY = 'SETTINGS_USER_CHANGE_CITY'
export const SETTINGS_USER_CHANGE_COUNTRY = 'SETTINGS_USER_CHANGE_COUNTRY'
export const SETTINGS_USER_CHANGE_PINCODE = 'SETTINGS_USER_CHANGE_PINCODE'
export const SETTINGS_USER_CHANGE_MOBILE_NUMBER = 'SETTINGS_USER_CHANGE_MOBILE_NUMBER'
export const SETTINGS_USER_CHANGE_DATE_OF_BIRTH = 'SETTINGS_USER_CHANGE_DATE_OF_BIRTH'
export const SETTINGS_USER_CHANGE_ADDRESS = 'SETTINGS_USER_CHANGE_ADDRESS'
