

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const REGISTER_LOADING = 'REGISTER_LOADING'

export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const MAIN_LOADING = 'MAIN_LOADING'

// Different Errors for the snackbar 
export const SNACKBAR_RESET = 'SNACKBAR_RESET'
export const ERROR_400 = 'ERROR_400'
export const ERROR_401 = 'ERROR_401'
export const ERROR_500 = 'ERROR_500'
export const ERROR_SOMETHING_ELSE = 'ERROR_SOMETHING_ELSE'
export const SUCCESS_200 = 'SUCCESS_200'

// Login
export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_LOADING_COMPLETE = 'LOGIN_LOADING_COMPLETE'
export const LOGIN_LOADING_ERROR = 'LOGIN_LOADING_ERROR'
export const LOGIN_LOADING_ERROR_RESOLVED = 'LOGIN_LOADING_ERROR_RESOLVED'

// Clients minimize tabs
export const CLIENTS_MINIMIZE_TAB = 'CLIENTS_MINIMIZE_TAB'
export const CLOSE_CLIENTS_MINIMIZE_TAB = 'CLOSE_CLIENTS_MINIMIZE_TAB'

// Add Profiles
export const ADD_OWNER_LOADING = 'ADD_OWNER_LOADING'

// Search Owner
export const SEARCH_OWNER = 'SEARCH_OWNER'
export const SEARCH_OWNER_LOADING = 'SEARCH_OWNER_LOADING'
export const ADD_ID_FROM_SEARCH_OWNER = 'ADD_ID_FROM_SEARCH_OWNER'

// Add Pet
export const ADD_PET_LOADING = 'ADD_PET_LOADING'
export const ADD_PET_LOADING_COMPLETE = 'ADD_PET_LOADING_COMPLETE'
export const ADD_PET_RESET = 'ADD_PET_RESET'
export const GET_PET_DETAILS_FROM_OWNER_ID_LOADING = 'GET_PET_DETAILS_FROM_OWNER_ID_LOADING'

// Clients List all get
export const CLIENTS_LIST_ALL_LOADING = 'CLIENTS_LIST_ALL_LOADING'
export const CLIENTS_LIST_ALL_LOADING_COMPLETE = 'CLIENTS_LIST_ALL_LOADING_COMPLETE'
export const CLIENTS_LIST_RESET = 'CLIENTS_LIST_RESET'


// Clients Search 
export const SEARCH_CLIENTS_LOADING = 'SEARCH_CLIENTS_LOADING'
export const SEARCH_CLIENTS = 'SEARCH_CLIENTS'
export const SEARCH_CLIENTS_RESET = 'SEARCH_CLIENTS_RESET'

export const SEARCH_CLIENTS_FOR_RECORD_LOADING = 'SEARCH_CLIENTS_FOR_RECORD_LOADING'
export const SEARCH_CLIENTS_FOR_RECORD = 'SEARCH_CLIENTS_FOR_RECORD'

// Clients Check 
export const CLIENTS_LIST_CHECK_INACTIVE = 'CLIENTS_LIST_CHECK_INACTIVE'
export const CLIENTS_LIST_CHECK_ACTIVE = 'CLIENTS_LIST_CHECK_ACTIVE'

// Edit Menu  CLients 
export const HIDE_LIST_CARD = 'HIDE_LIST_CARD'
export const UNHIDE_LIST_CARD = 'UNHIDE_LIST_CARD'

// Edit Client Profile Loading 
export const EDIT_PROFILES_CLIENTS_LOADING = 'EDIT_PROFILES_CLIENTS_LOADING'
export const RESET_EDIT_PROFILES_CLIENTS_LOADING = 'RESET_EDIT_PROFILES_CLIENTS_LOADING'

// Edit Owner Profile 
export const INITIATE_OWNER_EDIT_PROFILE_VALUES = 'INITIATE_OWNER_EDIT_PROFILE_VALUES'
export const RESET_OWNER_EDIT_PROFILE_VALUES = 'RESET_OWNER_EDIT_PROFILE_VALUES'

// Edit Pet Profile
export const INITIATE_PET_EDIT_PROFILE_VALUES = 'INITIATE_PET_EDIT_PROFILE_VALUES'
export const RESET_PET_EDIT_PROFILE_VALUES = 'RESET_PET_EDIT_PROFILE_VALUES'
export const INITIATE_PET_EDIT_OWNER_PROFILE_VALUES = 'INITIATE_PET_EDIT_OWNER_PROFILE_VALUES'

// Delete Profile Loader
export const DELETE_CLIENTS_PROFILES_LOADING =
    'DELETE_CLIENTS_PROFILES_LOADING'
export const DELETE_CLIENTS_PROFILES_LOADING_COMPLETE =
    'DELETE_CLIENTS_PROFILES_LOADING_COMPLETE'

// Minimize tabs on dashboard
export const ADD_MINIMIZE_TAB = 'ADD_MINIMIZE_TAB'
export const CLOSE_ADD_MINIMIZE_TAB = 'CLOSE_ADD_MINIMIZE_TAB'   

export const CLEAR_VALUES_OF_ELEMENT_ADD = 'CLEAR_VALUES_OF_ELEMENT_ADD'   
export const CHANGE_VALUES_OF_ELEMENT_ADD = 'CHANGE_VALUES_OF_ELEMENT_ADD'   
export const CHANGE_VALUES_ELEMENT_IF_ARRAY_ADD = 'CHANGE_VALUES_ELEMENT_IF_ARRAY_ADD'   

export const ADD_ELEMENT_IF_ARRAY_PRESCRIPTION = 'ADD_ELEMENT_IF_ARRAY_PRESCRIPTION'   
export const DELETE_ELEMENT_IF_ARRAY_PRESCRIPTION = 'DELETE_ELEMENT_IF_ARRAY_PRESCRIPTION'   
export const CHANGE_VALUES_OF_ELEMENT_WITH_ARRAY_PRESCRIPTION = 'CHANGE_VALUES_OF_ELEMENT_WITH_ARRAY_PRESCRIPTION' 

export const ADD_ELEMENT_IF_ARRAY_PRODUCT = 'ADD_ELEMENT_IF_ARRAY_PRODUCT'   
export const DELETE_ELEMENT_IF_ARRAY_PRODUCT = 'DELETE_ELEMENT_IF_ARRAY_PRODUCT'   


// Logout
export const LOGOUT = 'LOGOUT'

// ------------------------- SIDEBAR ---------------------------
export const MOUSE_ENTER = 'MOUSE_ENTER'
export const MOUSE_LEAVE = 'MOUSE_LEAVE'
export const ENABLE_HOVER = 'ENABLE_HOVER'
export const DISABLE_HOVER = 'DISABLE_HOVER'
export const HOVER_INIT = 'HOVER_INIT' 

// ------------------------- METRICS -------------------------
export const NUMBER_OF_VISITORS = 'NUMBER_OF_VISITORS'
export const NUMBER_OF_VISITORS_LOADING = 'NUMBER_OF_VISITORS_LOADING'
export const NUMBER_OF_VISITORS_LOADING_COMPLETE = 'NUMBER_OF_VISITORS_LOADING_COMPLETE'

export const  NUMBER_OF_APPOINTMENTS_CHART = ' NUMBER_OF_APPOINTMENTS_CHART'
export const  NUMBER_OF_APPOINTMENTS_CHART_LOADING = ' NUMBER_OF_APPOINTMENTS_CHART_LOADING'
export const  NUMBER_OF_APPOINTMENTS_CHART_LOADING_COMPLETE = ' NUMBER_OF_APPOINTMENTS_CHART_LOADING_COMPLETE'

export const  TYPE_OF_VISIT_CHART = ' TYPE_OF_VISIT_CHART'
export const  TYPE_OF_VISIT_CHART_LOADING = ' TYPE_OF_VISIT_CHART_LOADING'
export const  TYPE_OF_VISIT_CHART_LOADING_COMPLETE = ' TYPE_OF_VISIT_CHART_LOADING_COMPLETE'

export const  TOTAL_REVENUE_BLOCK = ' TOTAL_REVENUE_BLOCK'
export const  TOTAL_REVENUE_BLOCK_LOADING = ' TOTAL_REVENUE_BLOCK_LOADING'
export const  TOTAL_REVENUE_BLOCK_LOADING_COMPLETE = ' TOTAL_REVENUE_BLOCK_LOADING_COMPLETE'
export const  TOTAL_REVENUE_BLOCK_TODAY = ' TOTAL_REVENUE_BLOCK_TODAY'

// ----------------------------- WEBSITE ------------------------------
export const CHECK_INSTA_CONNECTED_LOADING = ' CHECK_INSTA_CONNECTED_LOADING'
export const CHECK_INSTA_CONNECTED_LOADING_COMPLETE = ' CHECK_INSTA_CONNECTED_LOADING_COMPLETE'
export const CHECK_INSTA_CONNECTED_RESET = ' CHECK_INSTA_CONNECTED_RESET'

export const GET_POSTS_FROM_INSTA_LOADING = ' GET_POSTS_FROM_INSTA_LOADING'
export const GET_POSTS_FROM_INSTA_LOADING_COMPLETE = ' GET_POSTS_FROM_INSTA_LOADING_COMPLETE'
export const GET_POSTS_FROM_INSTA_CONNECTED_RESET = ' GET_POSTS_FROM_INSTA_CONNECTED_RESET'

export const GET_POSTS_FROM_INSTA_TWO_LOADING = ' GET_POSTS_FROM_INSTA_TWO_LOADING'
export const GET_POSTS_FROM_INSTA_LOADING_TWO_COMPLETE = ' GET_POSTS_FROM_INSTA_LOADING_TWO_COMPLETE'
export const GET_POSTS_FROM_INSTA_CONNECTED_TWO_RESET = ' GET_POSTS_FROM_INSTA_CONNECTED_TWO_RESET'

export const MAKE_POST_LIVE = ' MAKE_POST_LIVE'
export const MAKE_POST_UNLIVE = ' MAKE_POST_UNLIVE'

export const EDIT_POST_CAPTION = ' EDIT_POST_CAPTION'
export const RESET_POST_CAPTION = ' RESET_POST_CAPTION'

export const ENABLE_POST_NSFW_WARNING = ' ENABLE_POST_NSFW_WARNING'
export const DISABLE_POST_NSFW_WARNING = ' DISABLE_POST_NSFW_WARNING'

export const CHECK_WEBSITE = ' CHECK_WEBSITE'
export const CHECK_WEBSITE_LOADING = ' CHECK_WEBSITE_LOADING'


// ------------------------- CORE SETTINGS ----------------------
export const SETTINGS_ENABLE = 'SETTINGS_ENABLE'
export const SETTINGS_DISABLE = 'SETTINGS_DISABLE'

// ---------------------- NOTIFICATIONS -------------------------

export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'
export const NOTIFICATIONS_LOADING = 'NOTIFICATIONS_LOADING'
export const NOTIFICATIONS_UNREAD_COUNT = 'NOTIFICATIONS_UNREAD_COUNT'
export const NOTIFICATION_STATUS = 'NOTIFICATION_STATUS'
export const NOTIFICATIONS_COUNT_CHANGE = 'NOTIFICATIONS_COUNT_CHANGE'

// ------------------ WEBSITE STORE DETAILS -----------------------------
export const STORE_DETAILS_LOADING = 'STORE_DETAILS_LOADING'
export const STORE_DETAILS = 'STORE_DETAILS'
export const GET_STORE_DETAILS_ALLOW = 'GET_STORE_DETAILS_ALLOW'
export const ADD_NEW_STORE_DETAILS = 'ADD_NEW_STORE_DETAILS'

// ---------------------------- RIGHTBAR -------------------------
export const EXPAND_RIGHTBAR =
    'EXPAND_RIGHTBAR'   
export const DEFLATE_RIGHTBAR =
    'DEFLATE_RIGHTBAR'   
export const IS_MOUNTED_RIGHTBAR =
    'IS_MOUNTED_RIGHTBAR'   

// ------------------------- EVENTS ----------------------------------
export const CHANGE_UPCOMING_EVENT_PREFIX = 'CHANGE_UPCOMING_EVENT_PREFIX'
export const LOAD_UPCOMING_EVENTS = 'LOAD_UPCOMING_EVENTS'